<?php include_once 'templates/header.phtml';

?>
<form action="modificarEspecies" method="POST" class="my-4">
    <div class="oculto">
        <input type="number" name="id_especie" value="<?=$categoria->id_especie?>"/>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Especie</label>
                <input required name="especie" type="text" class="form-control" value="<?=$categoria->especie?>"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Descripcion</label>
                <textarea required name="descripcion" class="form-control" rows="5"><?=$categoria->descripcion?></textarea>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Modificar</button>
</form>
  
<?php include_once 'templates/footer.phtml';