<?php 
    require 'templates/header.phtml';
    if (isset($_SESSION['USER_ID'])){
        require 'templates/form_subida_individuos.phtml';
    }
     
?>

<ul class="list-group">
<?php foreach($individuos as $individuo) : ?>
    <li class="list-group-item item-task">
        <div>
            <h5><b>Nombre: <?= $individuo->nombre ?></b></h5> 
            <h6>Especie: <?= $individuo->especie ?></h6>
            <h6>Color: <?= $individuo->color ?></h6>
            <h6>Edad (años): <?= $individuo->edad ?></h6>
        </div>
        <div class="actions">
            <a href="individuo/<?= $individuo->id?>" type="button" class='btn btn-success ml-auto'>Ver mas</a>
            <?php if (isset($_SESSION['USER_ID'])) : ?>
            <a href="individuoAModificar/<?= $individuo->id ?>" type="button" class='btn btn-secondary ml-auto'>Modificar</a>
            <a href="eliminarIndividuo/<?= $individuo->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            <?php endif ?>
        </div>
    </li>
<?php endforeach ?>
</ul>

<?php require 'templates/footer.phtml'; ?>