<?php 
    require 'templates/header.phtml';
    if (isset($_SESSION['USER_ID'])){
        require 'templates/form_subida_categorias.phtml'; 
    }
?>

<ul class="list-group">
<?php foreach($categorias as $categoria) : ?>
    <li class="list-group-item item-task">
        <div class="col-9">
            <h5><b>Especie: <?= $categoria->especie ?></b></h5> 
            <p>Descripcion: <?= $categoria->descripcion ?></p>
        </div>
        <div class="actions">
            <a href="especie/<?= $categoria->id_especie?>" type="button" class='btn btn-success ml-auto'>Ver</a>
            <?php if (isset($_SESSION['USER_ID'])) : ?>
            <a href="especieAModificar/<?= $categoria->id_especie ?>" type="button" class='btn btn-secondary ml-auto'>Modificar</a>
            <a href="borrarEspecie/<?= $categoria->id_especie ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a> 
            <?php endif ?>
        </div>
    </li>
<?php endforeach ?>
</ul>

<?php require 'templates/footer.phtml'; ?>